FROM tomcat:7
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml 
COPY context.xml /usr/local/tomcat/conf/context.xml
ADD settings.xml /usr/local/tomcat/conf/settings.xml
ADD api.war /usr/local/tomcat/webapps/api.war

